spring:
  profiles:
    active: postgresql

# uncomment below logging details so that you can see each step of the debug process while the application is getting executed

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG


# our verification token expiry date for registering a new user
verification:
  Token:
    expiry:
      seconds: 600


# user's frontend application url . when user goes to this frontend url it is going to call our backend to verify the user
frontend:
  applicationUrl:
    user:
      api: http://pavansingerreddy.tech
# data related to the public key private key and the expiry time of the jwt in seconds from when the jwt is first issued
jwt:
  public:
    key: classpath:publicKey.pem
  private:
    key: classpath:privateKey.pem
  token:
    expiry: 
      seconds: 60000


#our custom mail configuration
mail:
  config1:
    host: #enter your smtp server like smtp-mail.outlook.com for outlook etc...
    port: 587
    username:  #enter your email id of the email account which is assosiated with the above smtp
    password: #enter the app password of your email account
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
  config2:
    host: #enter your smtp server like smtp-mail.outlook.com for outlook etc...
    port: 587
    username: #enter your email id of the email account which is assosiated with the above smtp
    password: #enter the app password of your email account
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
